
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pru
  username: robinson
  password: admin1234
  host: localhost
  port: 5432


test:
  <<: *default
  database: pru
  username: robinson
  password: admin1234
  host: localhost
  port: 5432


production:
  <<: *default
  database: pru
  username: robinson
  password: <%= ENV["PRU_DATABASE_PASSWORD"] %>
